///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace RanorexLogInJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the RanorexLogInJenkinsRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("238cd5d6-5080-4e0b-a46c-02d2408aed3f")]
    public partial class RanorexLogInJenkinsRepository : RepoGenBaseFolder
    {
        static RanorexLogInJenkinsRepository instance = new RanorexLogInJenkinsRepository();
        RanorexLogInJenkinsRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;
        RanorexLogInJenkinsRepositoryFolders.BMCRemedyMidTier91LoginAppFolder _bmcremedymidtier91login;

        /// <summary>
        /// Gets the singleton class instance representing the RanorexLogInJenkinsRepository element repository.
        /// </summary>
        [RepositoryFolder("238cd5d6-5080-4e0b-a46c-02d2408aed3f")]
        public static RanorexLogInJenkinsRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public RanorexLogInJenkinsRepository() 
            : base("RanorexLogInJenkinsRepository", "/", null, 0, false, "238cd5d6-5080-4e0b-a46c-02d2408aed3f", ".\\RepositoryImages\\RanorexLogInJenkinsRepository238cd5d6.rximgres")
        {
            _applicationundertest = new RanorexLogInJenkinsRepositoryFolders.ApplicationUnderTestAppFolder(this);
            _bmcremedymidtier91login = new RanorexLogInJenkinsRepositoryFolders.BMCRemedyMidTier91LoginAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("238cd5d6-5080-4e0b-a46c-02d2408aed3f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("b1356308-6cc6-4b58-a175-5e28ab3124a1")]
        public virtual RanorexLogInJenkinsRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }

        /// <summary>
        /// The BMCRemedyMidTier91Login folder.
        /// </summary>
        [RepositoryFolder("a8e84aec-5c0e-4d2f-90a8-58d07ffb028d")]
        public virtual RanorexLogInJenkinsRepositoryFolders.BMCRemedyMidTier91LoginAppFolder BMCRemedyMidTier91Login
        {
            get { return _bmcremedymidtier91login; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class RanorexLogInJenkinsRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("b1356308-6cc6-4b58-a175-5e28ab3124a1")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _loginInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='desktop-c80mesn']", parentFolder, 30000, null, false, "b1356308-6cc6-4b58-a175-5e28ab3124a1", "")
            {
                _loginInfo = new RepoItemInfo(this, "Login", ".//input[#'login']", 30000, null, "116b5b93-33d9-430e-8880-f6f88c465a14");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("b1356308-6cc6-4b58-a175-5e28ab3124a1")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("b1356308-6cc6-4b58-a175-5e28ab3124a1")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Login item.
            /// </summary>
            [RepositoryItem("116b5b93-33d9-430e-8880-f6f88c465a14")]
            public virtual Ranorex.InputTag Login
            {
                get
                {
                    return _loginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Login item info.
            /// </summary>
            [RepositoryItemInfo("116b5b93-33d9-430e-8880-f6f88c465a14")]
            public virtual RepoItemInfo LoginInfo
            {
                get
                {
                    return _loginInfo;
                }
            }
        }

        /// <summary>
        /// The BMCRemedyMidTier91LoginAppFolder folder.
        /// </summary>
        [RepositoryFolder("a8e84aec-5c0e-4d2f-90a8-58d07ffb028d")]
        public partial class BMCRemedyMidTier91LoginAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameidInfo;
            RepoItemInfo _pwdidInfo;

            /// <summary>
            /// Creates a new BMCRemedyMidTier91Login  folder.
            /// </summary>
            public BMCRemedyMidTier91LoginAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BMCRemedyMidTier91Login", "/dom[@domain='desktop-c80mesn']", parentFolder, 30000, null, false, "a8e84aec-5c0e-4d2f-90a8-58d07ffb028d", "")
            {
                _usernameidInfo = new RepoItemInfo(this, "UsernameId", ".//input[#'username-id']", 30000, null, "d123c787-4e54-4fc4-9f00-63f577b682cc");
                _pwdidInfo = new RepoItemInfo(this, "PwdId", ".//input[#'pwd-id']", 30000, null, "4f9dd0e4-69b2-465d-96de-eabe08eff32f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a8e84aec-5c0e-4d2f-90a8-58d07ffb028d")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a8e84aec-5c0e-4d2f-90a8-58d07ffb028d")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UsernameId item.
            /// </summary>
            [RepositoryItem("d123c787-4e54-4fc4-9f00-63f577b682cc")]
            public virtual Ranorex.InputTag UsernameId
            {
                get
                {
                    return _usernameidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UsernameId item info.
            /// </summary>
            [RepositoryItemInfo("d123c787-4e54-4fc4-9f00-63f577b682cc")]
            public virtual RepoItemInfo UsernameIdInfo
            {
                get
                {
                    return _usernameidInfo;
                }
            }

            /// <summary>
            /// The PwdId item.
            /// </summary>
            [RepositoryItem("4f9dd0e4-69b2-465d-96de-eabe08eff32f")]
            public virtual Ranorex.InputTag PwdId
            {
                get
                {
                    return _pwdidInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The PwdId item info.
            /// </summary>
            [RepositoryItemInfo("4f9dd0e4-69b2-465d-96de-eabe08eff32f")]
            public virtual RepoItemInfo PwdIdInfo
            {
                get
                {
                    return _pwdidInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
