///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace RanorexLogInJenkins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Recording1 recording.
    /// </summary>
    [TestModule("99df9e33-3015-4d18-9b7a-23c8ad6a5d6a", ModuleType.Recording, 1)]
    public partial class Recording1 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the RanorexLogInJenkinsRepository repository.
        /// </summary>
        public static RanorexLogInJenkinsRepository repo = RanorexLogInJenkinsRepository.Instance;

        static Recording1 instance = new Recording1();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Recording1()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Recording1 Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'BMCRemedyMidTier91Login.UsernameId' at Center", repo.BMCRemedyMidTier91Login.UsernameIdInfo, new RecordItemIndex(0));
            repo.BMCRemedyMidTier91Login.UsernameId.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'georgi' with focus on 'BMCRemedyMidTier91Login.UsernameId'.", repo.BMCRemedyMidTier91Login.UsernameIdInfo, new RecordItemIndex(1));
            repo.BMCRemedyMidTier91Login.UsernameId.PressKeys("georgi");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'BMCRemedyMidTier91Login.PwdId' at Center", repo.BMCRemedyMidTier91Login.PwdIdInfo, new RecordItemIndex(2));
            repo.BMCRemedyMidTier91Login.PwdId.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(3));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'P@ssw0rd' with focus on 'BMCRemedyMidTier91Login.PwdId'.", repo.BMCRemedyMidTier91Login.PwdIdInfo, new RecordItemIndex(4));
            repo.BMCRemedyMidTier91Login.PwdId.PressKeys("P@ssw0rd");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ApplicationUnderTest.Login' at Center", repo.ApplicationUnderTest.LoginInfo, new RecordItemIndex(5));
            repo.ApplicationUnderTest.Login.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(6));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating NotExists on item 'BMCRemedyMidTier91Login.UsernameId'.", repo.BMCRemedyMidTier91Login.UsernameIdInfo, new RecordItemIndex(7));
            Validate.NotExists(repo.BMCRemedyMidTier91Login.UsernameIdInfo);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
